name: Build site
on:
  pull_request:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get yarn cache
      id: get-yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.get-yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          
    - name: Yarn Install
      uses: ianwalter/puppeteer@v3.0.0
      with:
        args: yarn install --frozen-lockfile
    - name: Yarn Build
      uses: ianwalter/puppeteer@v3.0.0
      with:
        args: yarn build
      env:
        CI: true
