name: Build site
on:
  pull_request:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install
      uses: ianwalter/puppeteer@3.0.0
      with:
        args: npm install

    - name: Build
      uses: ianwalter/puppeteer@3.0.0
      with:
        args: npm run-script build
      env:
        CI: true
