name: Publish site
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Cache compressed image files
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-images-${{ hashFiles('**/*.png', '**/*.jpe?g', '**/*.gif', '**/*.svg') }}
        restore-keys: ${{ runner.os }}-images-

    - name: Install
      uses: ianwalter/puppeteer@3.0.0
      with:
        args: npm install 

    - name: Build
      uses: ianwalter/puppeteer@3.0.0
      with:
        args: npm build
      env:
        CI: true

    - name: GH Pages publish
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: 'build/'
        GH_PAT: ${{ secrets.GH_PAT }}
