name: Build site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Yarn Install
      uses: nuxt/actions-yarn@master
      working-directory: ways-to-play
      with:
        args: install
    - name: Yarn Build
      uses: nuxt/actions-yarn@master
      working-directory: ways-to-play
      with:
        args: build
      env:
        CI: true
